services:
  flowise:
    image: flowiseai/flowise:latest
    ports:
      - '3020:3020'
    environment:
      - FLOWISE_USERNAME=admin
      - FLOWISE_PASSWORD=admin
      - PORT=3020
    volumes:
      - flowise-data:/root/.flowise
    entrypoint: /bin/sh -c "sleep 3; flowise start"
    extra_hosts:
        - "host.docker.internal:host-gateway"

  chroma:
    image: chromadb/chroma:0.5.13
    ports:
      - 8000:8000
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    volumes:
      - chroma-data:/chroma/chroma

  db:
    image: postgres:16
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  flowise-data:
  chroma-data:
  postgres-data:
